name: Cocktails App

on:
  push:
    branches: ['**'] # Sur tous les branches
  pull_request:
    branches: ['**'] # Sur toutes les PR

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.18.0] # La valeur doit être dans une liste

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build --if-present
